Portfolio website at Microverse Day 3
XRichardroidX/My-Microverse-Portfolio pull request #1
Opened 2022-09-21 19:59 UTC by XRichardroidX

This is the first part of the microverse portfolio site task, and the welcome page of this site is ready to be deployed.

2022-09-21 21:00 UTC, vickymarz requested changes
Hi @XRichardroidX  

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅  
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-21 21:00 UTC, victorokoroji commented on index.html
> +    </div>
- [ ] I think it will be better if you wrap use `<header>` tag instead of `<div class="head">` to make your website semantic because the header represents the introductory section of your website which will thus increase your website accessibility 😄 . You can check out this [link](<div class="head">) for more information 👍🏽

2022-09-21 21:00 UTC, victorokoroji commented on index.html
> +        <div class="welcome">welcome</div>
- [ ] I think it will be better if you make your logo clickable by wrapping it in an anchor `<a>` tag so that it will be easy for users to navigate through your website which is a very good user experience 😄

2022-09-21 21:00 UTC, victorokoroji commented on index.html
> +        </div>
- [ ] Kindly note that your hamburger will represent the navigation links of your website when you eventually add it, so to make your website semantic, it will be better if you wrap your hamburger in a `<nav>` tag instead of `<div class="menu">` so that screen readers and search engines will understand that the particular section is for navigations 👍🏽

2022-09-21 21:00 UTC, victorokoroji commented on index.html
> +  <div class="welcome-image">
- [ ] I think will be better if you wrap the container of your welcome page in a `<section>` tag instead of `<div class="welcome-image">` because `<section>` represent the thematic grouping of elements and are standalone so it makes sense if you use `section` tag which will increase your website accessibility.

2022-09-21 21:00 UTC, victorokoroji commented on index.html
> +    <div class="welcome-message-2">I'm a software developer</div>
- [ ] if you want that google (and other search engines) know about a specific topic, in this case, you, use a `<h1>` tag for your introductory text instead of  `<div class="welcome-message-1">Hey there. I'm Richard</div>` . [Check this link](https://www.reliablesoft.net/h1-tag/) for more info.

2022-09-21 21:00 UTC, victorokoroji commented on index.html
> +    <div class="welcome-message-2">I'm a software developer</div>
- [ ] Kindly ensure that your sub-subtitle uses a header tag `hx (e.g. <h2>,<h3>, etc...)` instead of  `<div class="welcome-message-2">I'm a software developer</div>` which will make your website semantic which will inturn increase its accessibility 👍🏽

2022-09-21 21:00 UTC, victorokoroji commented on index.html
> +    </div>
- [ ] I think it will be better if your list of icons is wrapped in `ul` tag to group them since the icons are a list, and also wrap each icon in  a `li` tag with each icon being a link (`a` tag)

e.g. 

 ```
<ul class="social-media">
        <li id="angellist">
            <a href="">
                <img src="images/angellist.png" alt="angellist">
            </a>
        </li>
         <li id="medium">
            <a href="">
                <img src="images/medium.png" alt="medium">
            </a>
        </li>
       ...
    </ul>
```

2022-09-21 21:00 UTC, victorokoroji commented on index.html
> +    <div class="head">
- [ ] Kindly ensure that the content of your toolbar section such as the logo and the hamburger matches the Figma design you chose 👍🏽 . Kindly adjust the font-weight and font sizes of your toolbar.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63473584/191606678-73e08298-d784-4341-8b78-1c5ba6f2e914.png)  |![image](https://user-images.githubusercontent.com/63473584/191606627-0db7ab18-83f4-41db-9271-69a3dd5972d3.png)  |

2022-09-21 21:00 UTC, victorokoroji commented on index.html
> +  <div class="welcome-image">
- [ ] I can see that the spacing between your toolbar and your headline section is too much. Please reduce it so that it matches the Figma design you chose 👍🏽 

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63473584/191607344-6df38d6b-4df1-48ab-a773-1b9f460257cb.png)  |![image](https://user-images.githubusercontent.com/63473584/191607452-df9179ac-0ff4-44bd-88ab-4115a3fa85a6.png)  |

2022-09-21 21:00 UTC, victorokoroji commented on index.html
> +    <div class="welcome-message-2">I'm a software developer</div>
- [ ] Kindly ensure that the color, font size, and font weight of the headline text match the Figma design you chose. You can check out the Figma design specification for the exact properties used👍🏽 

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63473584/191607857-606f0f30-3439-4184-9f9d-41d2095ada0e.png)  |![image](https://user-images.githubusercontent.com/63473584/191608219-6d2dd00b-232f-46f9-b565-d2add4d11cb7.png)  |

2022-09-21 21:00 UTC, victorokoroji commented on index.html
> +    <!-- Welcome page -->
- [ ] I can see that your welcome section contents are not centralized just like the Figma design template you chose. To make the content centralized, I would suggest you style the entire content using flexbox which will give the webpage a better alignment 👍🏽 


| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63473584/191609116-6687681a-b5b0-4e82-b133-29022e17b2f8.png)  |![image](https://user-images.githubusercontent.com/63473584/191609311-b57816d2-648d-4b11-9068-63dba837d604.png)  |

2022-09-22 00:35 UTC, Nyame-Wolf approved these changes
# STATUS: APPROVED :heavy_check_mark: :green_circle: 

Hi @XRichardroidX  :smile: , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://media.giphy.com/media/l4q7TIW8nEZYOJUf6/giphy.gif)


## Highlights :sparkles:
- Professional readme
- Linters are correctly set up and are passing
- Correct gitflow used

- [ ] [OPTIONAL] Kindly note that your pull request needs to have a descriptive summary. Enumerate in bullet points what you achieved. This ensures that a reviewer can know the scope of your project. Failure to have this, you may have your submission invalidated

## Optional suggestions :ballot_box_with_check: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

APPROVED! 💯 💯 💯

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me, @Nyame-Wolf in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 00:35 UTC, Nyame-Wolf commented on README.md
> +This project is [MIT](./MIT.md) licensed.
[OPTIONAL] Kindly add a Licence file to your repo. Currently this link does opens an empty [404 page](https://github.com/XRichardroidX/My-Microverse-Portfolio/blob/Feature-Branch/MIT.md) it should link to a file called MIT.md which should contain a licence. The note below gives instructions on how to add one.

2022-09-22 00:35 UTC, Nyame-Wolf commented on index.html
> +    </ul>
[OPTIONAL]Good job changing this icons into links. Please note however that the bullets still appear. This are the default list style type. Please style the list type as none:
in the css`.social-media{
list-style-type: none}`

2022-09-22 00:35 UTC, Nyame-Wolf commented on README.md
>  Feel free to check the [issues page](../../issues/).
[OPTIONAL] This should link to  the issues page of your current project project. Currently this link is still broken
To add this, on the project, click on issues and copy the link. replace the `(../../issuses/)` with the link you copy.
<img width="1661" alt="Screenshot 2022-09-22 at 03 23 50" src="https://user-images.githubusercontent.com/48546992/191632568-ed17077f-e3f3-4df8-a478-c3252c85fb22.png">

2022-09-22 00:35 UTC, Nyame-Wolf commented on style.css
> +
[OPTIONAL] Kindly note that your page currently is scrolling in mobile view.
<img width="1669" alt="Screenshot 2022-09-22 at 03 11 18" src="https://user-images.githubusercontent.com/48546992/191632821-fe9671aa-32f9-488f-8d88-89ce5c3f4b95.png">
<img width="1670" alt="Screenshot 2022-09-22 at 03 11 23" src="https://user-images.githubusercontent.com/48546992/191632824-8b469116-71a3-406a-ba0c-bf8e18e453ae.png">
 
Your page should fit the mobile device width and should not scroll. The scroll provides a bad user experience to users of your app or project.

2022-09-22 00:46 UTC, merged

2022-09-22 01:00 UTC, XRichardroidX commented on style.css
> +
@Nyame-Wolf How do I make my web page not to be scrollable?, I will need your assistance on that.